[package]
name = "elerem"
version = "0.1.0"
edition = "2024"

[dependencies]
stefn = { git = "file:///home/lucas/Projects/stefn", branch = "master"}
#stefn = { git = "https://github.com/lucas-montes/stefn" }

fuzzer = { path = "fuzzer" }

tokio = { workspace = true}
tokio-util = { version = "0.7.4", features = ["compat"] }
futures = "0.3.30"

tower-http = { version = "0.6.1", features = ["fs", "trace"] }

axum = { version = "0.8.1", features = ["multipart", "json", "query", "http2", "macros", "tracing", "ws"] }

utoipa = { version = "5.3.0", features = ["axum_extras", "chrono", "decimal"] }
utoipa-scalar = { version = "0.3", features = ["axum"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio", "tls-rustls", "postgres"]}

askama = "0.12.1"

oauth2 = "4.4.1"

validator = { version = "0.19", features = ["derive"] }

base64 = "0.22.1"
async-stripe = { version = "0.39.1", features = ["runtime-tokio-hyper-rustls"] }
reqwest = { workspace = true, features = ["json"] }

[workspace]
members = ["fuzzer"]


[workspace.dependencies]
reqwest = "0.12.24"

# Benchmarking
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
pprof = { version = "0.14.0", features = ["flamegraph", "criterion"] }

tokio = { version = "1.38.0", features = ["full"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.132", features = ["std"] }

chrono = "0.4.23"
