use crate::config::Configuration;
use std::time::Duration;

/// Test planner trait - generates test cases lazily using various algorithms
/// (IPOG, IPOG-C, T-wise Adaptive, Boundary Analysis, etc.)
pub trait TestPlanner: Iterator<Item = Case> {
    /// Create planner from configuration
    fn from_config(config: Configuration) -> Self
    where
        Self: Sized;

    /// Get algorithm name
    fn algorithm_name(&self) -> &'static str;

    /// Provide feedback to adaptive planners (optional)
    fn feedback(&mut self, _feedback: PlannerFeedback) {}
}

/// Feedback from scheduler to planner for adaptive test generation
#[derive(Debug, Clone)]
pub struct PlannerFeedback {
    pub case_id: String,
    pub success: bool,
    pub failure_rate: f64,
    pub response_time_p95: Duration,
}

/// A single test case generated by the planner
#[derive(Debug, Clone)]
pub struct Case {
    pub id: String,
    pub name: String,
    pub request_template: RequestTemplate,
    pub executor_type: ExecutorType,
    pub assertions: Vec<Assertion>,
    pub stopping_conditions: Vec<StoppingCondition>,
}

/// Request template for execution
#[derive(Debug, Clone)]
pub struct RequestTemplate {
    pub method: Method,
    pub url: String,
    pub headers: Vec<(String, String)>,
    pub body: Option<Vec<u8>>,
    pub query_params: Vec<(String, String)>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Get,
    Post,
    Put,
    Delete,
    Patch,
    Head,
    Options,
}

/// Execution strategy for a case
#[derive(Debug, Clone)]
pub enum ExecutorType {
    /// Execute once
    SingleShot,
    /// Constant number of VUsers
    ConstantVus { vus: usize, duration: Duration },
    /// Ramping VUsers over stages
    RampingVus { stages: Vec<Stage> },
    /// Constant arrival rate (open model)
    ConstantArrivalRate { rate: f64, duration: Duration, max_vus: usize },
}

#[derive(Debug, Clone)]
pub struct Stage {
    pub target_vus: usize,
    pub duration: Duration,
}

/// Assertions to validate during/after execution
#[derive(Debug, Clone)]
pub enum Assertion {
    StatusCode(u16),
    StatusRange(u16, u16),
    BodyContains(String),
    HeaderExists(String),
    P50ResponseTime { threshold: Duration },
    P95ResponseTime { threshold: Duration },
    P99ResponseTime { threshold: Duration },
    SuccessRate { min: f64 },
    ErrorRate { max: f64 },
}

/// Conditions that trigger early stopping of a case
#[derive(Debug, Clone)]
pub enum StoppingCondition {
    FailureRate { threshold: f64 },
    ConsecutiveErrors { count: usize },
    P95ResponseTime { threshold: Duration },
    P99ResponseTime { threshold: Duration },
    TotalErrors { max: usize },
    NoSuccessFor { duration: Duration },
}

// Example planner implementation: Boundary Value Analysis
pub struct BoundaryPlanner {
    config: Configuration,
    cases: Vec<Case>,
    current: usize,
}

impl TestPlanner for BoundaryPlanner {
    fn from_config(config: Configuration) -> Self {
        // TODO: Parse config and generate boundary test cases
        let cases = vec![]; // Would generate from API spec
        Self {
            config,
            cases,
            current: 0,
        }
    }

    fn algorithm_name(&self) -> &'static str {
        "Boundary Value Analysis"
    }
}

impl Iterator for BoundaryPlanner {
    type Item = Case;

    fn next(&mut self) -> Option<Case> {
        if self.current >= self.cases.len() {
            return None;
        }
        let case = self.cases[self.current].clone();
        self.current += 1;
        Some(case)
    }
}
